/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookMask: typeof import('./src/components/bookMask.vue')['default']
    CardBack: typeof import('./src/components/InnerCard/CardBack.vue')['default']
    CardFront: typeof import('./src/components/InnerCard/CardFront.vue')['default']
    CardGallery3D: typeof import('./src/components/CardGallery3D.vue')['default']
    CardPopup: typeof import('./src/components/CardPopup.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelpComponent: typeof import('./src/components/HelpComponent.vue')['default']
    'HelpComponent.': typeof import('./src/components/HelpComponent..vue')['default']
    MessageTip: typeof import('./src/components/tip/messageTip.vue')['default']
    RecoveryCode: typeof import('./src/components/RecoveryCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
