/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundScene: typeof import('./src/components/BackgroundScene.vue')['default']
    BookMask: typeof import('./src/components/bookMask.vue')['default']
    CardBack: typeof import('./src/components/InnerCard/CardBack.vue')['default']
    CardFront: typeof import('./src/components/InnerCard/CardFront.vue')['default']
    CardGallery3D: typeof import('./src/components/CardGallery3D.vue')['default']
    CardLog: typeof import('./src/components/DateComponent/CardLog.vue')['default']
    CardLogCard: typeof import('./src/components/DateComponent/CardLogCard.vue')['default']
    CardPopup: typeof import('./src/components/CardPopup.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmailCompotent: typeof import('./src/components/emailCompotent.vue')['default']
    EmailManagement: typeof import('./src/components/PersonalCenter/EmailManagement.vue')['default']
    HelpComponent: typeof import('./src/components/HelpComponent.vue')['default']
    'HelpComponent.': typeof import('./src/components/HelpComponent..vue')['default']
    MessageTip: typeof import('./src/components/tip/messageTip.vue')['default']
    MoodCalendar: typeof import('./src/components/DateComponent/MoodCalendar.vue')['default']
    MoodLog: typeof import('./src/components/DateComponent/MoodLog.vue')['default']
    MoodLogCard: typeof import('./src/components/DateComponent/MoodLogCard.vue')['default']
    RecoveryCode: typeof import('./src/components/RecoveryCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
